### PR TITLE
dataset cache

### LINKED ISSUE #29: ds cacheing in dock widget
The new widget (#27) is fairly minimal. One thing that would be good to add is some dataset cacheing -- right now every time the `load` button is hit, it will load the provded filename into a yt `ds`. Should be feasible to add a cache of that `ds` and selection objects as  attributes on the `ReaderWidget` so that subsequent loads do not need to rebuild those objects when just changing the field name. Would just need to watch for changes in the filename or selection parameters.

### PR DESCRIPTION
**Pull request by chrishavlin**
Working on a dataset cache...

The initial push simply stores weakrefs to yt datasets in a dictionary... definitely not threadsafe (but was in yt is?) but it might speed up consecutive loads of the same dataset. There also may be memory issues with always adding to the cache -- will want to have an option to enable/disable the cache. 

Closes #29 if it all works out...

### CODE REVIEW

**Comment by matthewturk** [comment]
> definitely not threadsafe (but was in yt is?)

Hey!  We do *some* threaded stuff.  ;-)  https://github.com/yt-project/yt-4.0-paper/pull/113

**Comment by chrishavlin** [comment]
latest push includes a yt-napari config file setup so that the cacheing can be disabled (and the option is remembered between napari sessions). The gui and json readers also now have a corresponding `store_in_cache` option (default value from config file).

**Comment by chrishavlin** [comment]
@matthewturk I think this is ready to go. wanna take a look? 

src/yt_napari/_ds_cache.py is the cache implementation. It now uses hard references rather than week references like we talked about. 

The  `dataset_cache` instance (in `src/yt_napari/_ds_cache.py`) will only be populated when loading data from the napari GUI (either loading from json or the interactive widget: adding data to napari from a jupyter notebook will not add a ds to the cache). I **could** implement some sort of teardown method tied to the loader widget (it's a `QWidget` instance, so there are methods you can override to catch destruction), but I don't see a reason to. I think the normal garbage collection during napari shutdown should be totally fine. 

The rest of the PR is mostly adding ways to control the cache behavior: I added a configuration file for yt-napari (`src/yt_napari/config.py`) so one can disable the caching if desired and have that option persist between napari sessions. It might come in handing for future work too... I loosely based it off of how yt handles configuration. Lemme know if you have thoughts on the implementation here.

**Comment by chrishavlin** [comment]
latest push uses the yt config file directly (at Matt's suggestion)!

**Pull request merged**
